### ISSUE TITLE
How to use distributed trainning?

### ISSUE THREAD

**Issue by haoyan14** [boheumd/D-NeRV#1]
Why when I use distributed training, I get stuck here in "model = torch.nn.parallel.DistributedDataParallel(model.to(local_rank), device_ids=[local_rank], output_device=local_rank, find_unused_parameters=False)"?

**Comment by bohemeta** [comment]
Hello, I did not come across this problem before. Can you provide more information about this issue?  If you change to the single gpu training, will it have the similar problem?

**Comment by boheumd** [comment]
Hello, I did not come across this problem before. Can you provide more information about this issue? If you change to the single gpu training, will it have the similar problem?

**Comment by haoyan14** [comment]
Sorry,i have solved the problem. The reason for this situation is that I mixed the use of "torchrun" and "-d".
